version: '2'
services:
  udacity-tensorflow:
    build: .
    image: lopezco/docker-tensorflow
    container_name: docker-tensorflow
    ports:
      - "8899:8899"
      - "8008:8008"
    volumes:
     - ./notebooks:/notebooks
    environment:
      JUPYTER_PASSWORD: "mypassword"
      JUPYTER_PORT: 8899
      TENSORBOARD_LOGDIR: ./logs
      TENSORBOARD_PORT: 8008

